### ISSUE TITLE
something wrong..

### ISSUE THREAD

**Issue by moveon7** [macanv/BERT-BiLSTM-CRF-NER#179]
when i run bert_base_serving_start to do NER, loading your model,something went wrong...

E:[36mNER_MODEL, Lodding...[0m:fail to optimize the graph! Can't load save_path when it is None.
Traceback (most recent call last):
  File "d:\py\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\py\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\py\Anaconda3\Scripts\bert-base-serving-start.exe\__main__.py", line 9, in <module>
  File "d:\py\anaconda3\lib\site-packages\bert_base\runs\__init__.py", line 17, in start_server
    server = BertServer(args)
  File "d:\py\anaconda3\lib\site-packages\bert_base\server\__init__.py", line 102, in __init__
    raise FileNotFoundError('graph optimization fails and returns empty result')
FileNotFoundError: graph optimization fails and returns empty result

**Comment by macanv** [comment]
please check your file put to correct dir
