### ISSUE TITLE
fail to optimize the graph! Can't load save_path when it is None.

### ISSUE THREAD

**Issue by MachineLearning4Work** [macanv/BERT-BiLSTM-CRF-NER#183]
Hi guys!

I tried to run sample code . however I am facing this error . All comments are very welcomed and appreciated in this matter.  

raise FileNotFoundError('graph optimization fails and returns empty result')
FileNotFoundError: graph optimization fails and returns empty result

More details : 

 File "/usr/local/lib/python3.6/site-packages/bert_base-0.0.9-py3.6.egg/bert_base/server/graph.py", line 295, in optimize_ner_model
    saver.restore(sess, tf.train.latest_checkpoint(args.model_dir))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1264, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
Traceback (most recent call last):
  File "/usr/local/bin/bert-base-serving-start", line 11, in <module>
    load_entry_point('bert-base==0.0.9', 'console_scripts', 'bert-base-serving-start')()
  File "/usr/local/lib/python3.6/site-packages/bert_base-0.0.9-py3.6.egg/bert_base/runs/__init__.py", line 17, in start_server
    server = BertServer(args)
  File "/usr/local/lib/python3.6/site-packages/bert_base-0.0.9-py3.6.egg/bert_base/server/__init__.py", line 102, in __init__
    raise FileNotFoundError('graph optimization fails and returns empty result')
FileNotFoundError: graph optimization fails and returns empty result

**Comment by Edwardnone** [comment]
我也出现这个问题

**Comment by JiaojiaoYe1994** [comment]
I have met the same error when I tried to run the server.

Have you guys solved this problem?

command:
bert-base-serving-start \
    -model_dir C:\workspace\python\BERT_Base\output\ner2 \
    -bert_model_dir F:\chinese_L-12_H-768_A-12
    -model_pb_dir C:\workspace\python\BERT_Base\model_pb_dir
    -mode NER

output:

FileNotFoundError: graph optimization fails and returns empty result
