### ISSUE TITLE
我在训练NER的时候，保存一个checkpoint，然后下一次从该checkpoint接着训练，参数相同，但遇到以下error message: ValueError: Shape of variable crf_loss/transitions:0 ((31, 31)) doesn't match with shape of tensor crf_loss/transitions ([33, 33]) from checkpoint reader.

### ISSUE THREAD

**Issue by johnny0213** [macanv/BERT-BiLSTM-CRF-NER#191]
我在训练NER的时候，保存一个checkpoint，然后下一次从该checkpoint接着训练，参数相同，但遇到以下error message: 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/bert-base-ner-train", line 11, in <module>
    load_entry_point('bert-base==0.0.9', 'console_scripts', 'bert-base-ner-train')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bert_base-0.0.9-py3.7.egg/bert_base/runs/__init__.py", line 38, in train_ner
    train(args=args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bert_base-0.0.9-py3.7.egg/bert_base/train/bert_lstm_ner.py", line 636, in train
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 362, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1154, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1184, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1142, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bert_base-0.0.9-py3.7.egg/bert_base/train/bert_lstm_ner.py", line 397, in model_fn
    tf.train.init_from_checkpoint(init_checkpoint, assignment_map)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 291, in init_from_checkpoint
    init_from_checkpoint_fn)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1684, in merge_call
    return self._merge_call(merge_fn, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1691, in _merge_call
    return merge_fn(self._strategy, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 286, in <lambda>
    ckpt_dir_or_file, assignment_map)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 329, in _init_from_checkpoint
    tensor_name_in_ckpt, str(variable_map[tensor_name_in_ckpt])
ValueError: Shape of variable crf_loss/transitions:0 ((31, 31)) doesn't match with shape of tensor crf_loss/transitions ([33, 33]) from checkpoint reader.

请问怎么解决这个问题？谢谢！

**Comment by johnny0213** [comment]
找到问题了，是我上次训练数据集的label数量与下次训练数据集的label数量不同导致。可在下次训练数据中补上缺失的label，使得label数量一致，即可继续训练了。

**Comment by Machine-Tom** [comment]
请教一下，你是怎么从某个checkpoint接着训练？

**Comment by gao-lex** [comment]
@johnny0213  怎么从监测点开始运行的呢？-clean参数不起作用啊

**Comment by huicao1995** [comment]
同问怎么从一个ckpt接着训练新的数据啊？谢谢大佬们
