### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by chenxiang567** [macanv/BERT-BiLSTM-CRF-NER#210]
Traceback (most recent call last):
  File "c:\users\lenovo-1\anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\bert_base\server\__init__.py", line 487, in run
    self._run()
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\zmq\decorators.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\bert_base\server\zmq_decor.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\bert_base\server\__init__.py", line 505, in _run
    for r in estimator.predict(input_fn=self.input_fn_builder(receivers, tf), yield_single_examples=False):
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 611, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\bert_base\server\__init__.py", line 463, in classification_model_fn
    pred_probs = tf.import_graph_def(graph_def, name='', input_map=input_map, return_elements=['pred_prob:0'])
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "c:\users\lenovo-1\anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 426, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'BatchMatMulV2' in binary running on DESKTOP-G31B25M. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by chenxiang567** [comment]
tf的版本问题
