### ISSUE TITLE
http请求报错

### ISSUE THREAD

**Issue by caseware66** [macanv/BERT-BiLSTM-CRF-NER#270]
RuntimeError: Too many concurrent connections!Try to increase the value of "max_concurrency", currently =500

**Comment by macanv** [comment]
信息太少，脑洞有限，无能为力。

**Comment by caseware66** [comment]
再请求的时候如果，文本有空格会报如下错误：Traceback (most recent call last):
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/server/http.py", line 58, in encode_query
    'result':bc.encode( text_list,text,is_tokenized=True)}
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 433, in arg_wrapper
    r = f if isinstance(f, dict) else f(*args, **kwargs)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 197, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 262, in encode
    self._check_input_lst_lst_str(texts)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 380, in _check_input_lst_lst_str
    BertClient._check_input_lst_str(s)
  File "/home/elasticsearch/cx/BERT-BiLSTM-CRF-NER-master/bert_base/client/__init__.py", line 370, in _check_input_lst_str
    'all elements in the list must be non-empty string, but element %d is %s' % (idx, repr(s)))
ValueError: all elements in the list must be non-empty string, but element 67 is ' '
如果最大连接设置为10，再请求10次，报10次该错误后，就会出现RuntimeError: Too many concurrent connections!Try to increase the value of "max_concurrency", currently =10

**Comment by macanv** [comment]
is_tokenized=True 请自行先tokenizer,然后再输入，如果使用wordpice ,请设置为False.

**Comment by caseware66** [comment]
您好，
&nbsp; &nbsp; wordpice是什么意思?


谢谢!



---原始邮件---
发件人: "MaCan"<notifications@github.com&gt;
发送时间: 2019年11月28日(周四) 上午10:01
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;;
抄送: "caseware66"<157500647@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] http请求报错 (#270)



is_tokenized=True 请自行先tokenizer,然后再输入，如果使用wordpice ,请设置为False.
