### ISSUE TITLE
服务部署成功后，按照bc.encode执行之后没有任何反馈的停滞了

### ISSUE THREAD

**Issue by tian231825** [macanv/BERT-BiLSTM-CRF-NER#279]
Traceback (most recent call last):
  File "bert_service.py", line 39, in <module>
    rst = bc.encode([str, str])  #测试同时输入两个句子，多个输入同理
  File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/__init__.py", line 197, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/__init__.py", line 276, in encode
    rst = self._recv_ndarray().content if blocking else None
  File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/__init__.py", line 152, in _recv_ndarray
    request_id, response = self._recv()
  File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/__init__.py", line 146, in _recv
    response = self.receiver.recv_multipart()
  File "/home/junruit/.local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 470, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
![QQ图片20191209132912](https://user-images.githubusercontent.com/22673317/70409767-ed28c280-1a87-11ea-9032-734e59ffa369.png)

**Comment by tian231825** [comment]
import time
from bert_base.client import BertClient
# 指定服务器的IP
with BertClient(ip='localhost:5555',  show_server_config=False, check_version=False, check_length=False, mode='NER') as bc:
    start_t = time.perf_counter()
    str = '1月24日，新华社对外发布了中央对雄安新区的指导意见，洋洋洒洒1.2万多字，17次提到北京，4次提到天津，信息量很大，其实也回答了人们关心的很多问题。'
    rst = bc.encode([str, str])  #测试同时输入两个句子，多个输入同理
    print('rst:', rst) 
    print(time.perf_counter() - start_t)

**Comment by tian231825** [comment]
![QQ图片20191209132912](https://user-images.githubusercontent.com/22673317/70409872-3f69e380-1a88-11ea-86fd-67486c4a0da7.png)
运行状态如图

**Comment by JensonXIE** [comment]
me too. 我在怀疑是不是我的训练数据标注的有问题，用别人公开数据训练并启动服务后运行客户端后能正常识别

**Comment by albert-jin** [comment]
不清楚，我这边有个更好的开源ner项目，你可以试试，要的话明天邮件发你



---原始邮件---
发件人: "JensonXIE"<notifications@github.com&gt;
发送时间: 2019年12月11日(周三) 凌晨0:04
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 服务部署成功后，按照bc.encode执行之后没有任何反馈的停滞了 (#279)



me too. 我在怀疑是不是我的训练数据标注的有问题，用别人公开数据训练并启动服务后运行客户端后能正常识别

**Comment by JensonXIE** [comment]
> 不清楚，我这边有个更好的开源ner项目，你可以试试，要的话明天邮件发你
> […](#)
> ---原始邮件--- 发件人: "JensonXIE"<notifications@github.com&gt; 发送时间: 2019年12月11日(周三) 凌晨0:04 收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 服务部署成功后，按照bc.encode执行之后没有任何反馈的停滞了 (#279) me too. 我在怀疑是不是我的训练数据标注的有问题，用别人公开数据训练并启动服务后运行客户端后能正常识别 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.



> 不清楚，我这边有个更好的开源ner项目，你可以试试，要的话明天邮件发你
> […](#)
> ---原始邮件--- 发件人: "JensonXIE"<notifications@github.com&gt; 发送时间: 2019年12月11日(周三) 凌晨0:04 收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 服务部署成功后，按照bc.encode执行之后没有任何反馈的停滞了 (#279) me too. 我在怀疑是不是我的训练数据标注的有问题，用别人公开数据训练并启动服务后运行客户端后能正常识别 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

链接发一下，thanks

**Comment by tian231825** [comment]
好的，非常感谢，能发下链接吗

**Comment by JensonXIE** [comment]
@ @tian231825 你试一下启动服务的时候设置参数-max_seq_len等于你训练的时候的值，源码里面默认是128

**Comment by tian231825** [comment]
> @ @tian231825 你试一下启动服务的时候设置参数-max_seq_len等于你训练的时候的值，源码里面默认是128
感觉还是不太行，预训练的模型直接使用还是算到一半就停了

**Comment by yahal333** [comment]
试一下将with BertClient(ip='localhost', ner_model_dir=ner_model_dir,port=23456, port_out=23457, show_server_config=False, check_version=False, check_length=False, mode='NER') as bc:
改成：with BertClient() as bc:

**Comment by tian231825** [comment]
> 试一下将with BertClient(ip='localhost', ner_model_dir=ner_model_dir,port=23456, port_out=23457, show_server_config=False, check_version=False, check_length=False, mode='NER') as bc:
> 改成：with BertClient() as bc:

哎，感觉这个方法修改之后也没什么变化
![image](https://user-images.githubusercontent.com/22673317/70890455-11544880-2020-11ea-938b-9a1d183e7228.png)

**Comment by quewentian** [comment]
> > 试一下将with BertClient(ip='localhost', ner_model_dir=ner_model_dir,port=23456, port_out=23457, show_server_config=False, check_version=False, check_length=False, mode='NER') as bc:
> > 改成：with BertClient() as bc:
> 
> 哎，感觉这个方法修改之后也没什么变化
> <img alt="QQ图片20191209132912" width="494" src="https://user-images.githubusercontent.com/22673317/70890548-4e203f80-2020-11ea-9a89-2cf1cb172dab.png">

啊！！！和我的一样啊！请问你解决这个问题了吗？

**Comment by Gailsunset** [comment]
同样遇到这个问题，请问如何解决。。
之前可以用，2个后再来看不能用了

**Comment by albert-jin** [comment]
哪需要这么麻烦，这模型最基础了，你这点问题问问百度不就解决了嘛，😂😂😂



---原始邮件---
发件人: "Gailsunset"<notifications@github.com&gt;
发送时间: 2020年6月10日(周三) 下午2:32
收件人: "macanv/BERT-BiLSTM-CRF-NER"<BERT-BiLSTM-CRF-NER@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"albert-jin"<248390697@qq.com&gt;;
主题: Re: [macanv/BERT-BiLSTM-CRF-NER] 服务部署成功后，按照bc.encode执行之后没有任何反馈的停滞了 (#279)




 
同样遇到这个问题，请问如何解决。。
 之前可以用，2个后再来看不能用了

**Comment by qubo** [comment]
估计是服务没起来，ps -fe | grep bert-base-serving-start

**Comment by SevenMpp** [comment]
> 
> 
> Traceback (most recent call last):
> File "bert_service.py", line 39, in
> rst = bc.encode([str, str]) #测试同时输入两个句子，多个输入同理
> File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 197, in arg_wrapper
> return func(self, *args, **kwargs)
> File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 276, in encode
> rst = self._recv_ndarray().content if blocking else None
> File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 152, in _recv_ndarray
> request_id, response = self._recv()
> File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 146, in _recv
> response = self.receiver.recv_multipart()
> File "/home/junruit/.local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 470, in recv_multipart
> parts = [self.recv(flags, copy=copy, track=track)]
> File "zmq/backend/cython/socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
> File "zmq/backend/cython/socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
> File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
> File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
> ![QQ图片20191209132912](https://user-images.githubusercontent.com/22673317/70409767-ed28c280-1a87-11ea-9032-734e59ffa369.png)

请问您解决这个问题了吗

**Comment by xianlv1988** [comment]
> > Traceback (most recent call last):
> > File "bert_service.py", line 39, in
> > rst = bc.encode([str, str]) #测试同时输入两个句子，多个输入同理
> > File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 197, in arg_wrapper
> > return func(self, *args, **kwargs)
> > File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 276, in encode
> > rst = self._recv_ndarray().content if blocking else None
> > File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 152, in _recv_ndarray
> > request_id, response = self._recv()
> > File "/home/junruit/.local/lib/python3.6/site-packages/bert_base/client/**init**.py", line 146, in _recv
> > response = self.receiver.recv_multipart()
> > File "/home/junruit/.local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 470, in recv_multipart
> > parts = [self.recv(flags, copy=copy, track=track)]
> > File "zmq/backend/cython/socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
> > File "zmq/backend/cython/socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
> > File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
> > File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
> > ![QQ图片20191209132912](https://user-images.githubusercontent.com/22673317/70409767-ed28c280-1a87-11ea-9032-734e59ffa369.png)
> 
> 请问您解决这个问题了吗

请问这个问题解决了吗？
