### ISSUE TITLE
 223万行数据，竟然说 training data is so small...

### ISSUE THREAD

**Issue by kcjevin** [macanv/BERT-BiLSTM-CRF-NER#289]
Traceback (most recent call last):
  File "c:\users\mydell\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mydell\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mydell\Anaconda3\Scripts\bert-base-ner-train.exe\__main__.py", line 9, in <module>
  File "c:\users\mydell\anaconda3\lib\site-packages\bert_base\runs\__init__.py", line 38, in train_ner
    train(args=args)
  File "c:\users\mydell\anaconda3\lib\site-packages\bert_base\train\bert_lstm_ner.py", line 554, in train
    raise AttributeError('training data is so small...')
AttributeError: training data is so small...

求助啊，求助，

**Comment by hwwzyh** [comment]
训练语料每句结束空一行就行了

**Comment by kcjevin** [comment]
> 训练语料每句结束空一行就行了

还是不行啊    training data is so small...

**Comment by kcjevin** [comment]
> 训练语料每句结束空一行就行了
文件体积已经20m了

**Comment by macanv** [comment]
不是你200万行数据不行，而是我代码不能处理你的数据格式。麻烦检查一下数据读取，是否能够满足你的要求。

**Comment by kcjevin** [comment]
> 不是你200万行数据不行，而是我代码不能处理你的数据格式。麻烦检查一下数据读取，是否能够满足你的要求。

谢谢，终于找到问题的根源了。我的数据 中间用的是 tab 分割的。程序里要求的是用空格分割。谢谢
