### ISSUE TITLE
训练时tensorflow没有相关属性

### ISSUE THREAD

**Issue by Ivan-Ji** [macanv/BERT-BiLSTM-CRF-NER#317]
```
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    train_ner()
  File "run.py", line 39, in train_ner
    train(args=args)
  File "/home/git_project/BERT-BiLSTM-CRF-NER/bert_base/train/bert_lstm_ner.py", line 619, in train
    early_stopping_hook = tf.contrib.estimator.stop_if_no_decrease_hook(
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'
```
我在项目文件里使用`python run.py命令`训练的时候出现了上述情况，我本地`tf`版本为`1.14.0`在网上也查过了这是`tf`的版本不对，所以想问一下`bert_base`文件夹下的`tf`版本是多少，能否更新一下最新的文件呢

**Comment by macanv** [comment]
1.13.1
