### ISSUE TITLE
stop_if_no_decrease_hook

### ISSUE THREAD

**Issue by ghost** [macanv/BERT-BiLSTM-CRF-NER#338]
early_stopping_hook = tf.contrib.estimator.stop_if_no_decrease_hook(
            estimator=estimator,
            metric_name='loss',
            max_steps_without_decrease=num_train_steps,
            eval_dir=None,
            min_steps=0,
            run_every_secs=None,
            run_every_steps=args.save_checkpoints_steps)
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'
early_stopping_hook = tf.estimator.experimental.stop_if_no_decrease_hook(
            estimator=estimator,
            metric_name='loss',
            max_steps_without_decrease=num_train_steps,
            eval_dir=None,
            min_steps=0,
            run_every_secs=None,
            run_every_steps=args.save_checkpoints_steps)
AttributeError: module 'tensorflow.estimator' has no attribute 'experimental'
tf.__version__ = '1.9.0'

**Comment by macanv** [comment]
please use tf version >= 1.13 or 1.14

**Comment by sonnydu** [comment]
> 1.13 or 1.14
TensorFlow -- 1.15.0
Traceback (most recent call last):
  File "/usr/local/bin/bert-base-ner-train", line 8, in <module>
    sys.exit(train_ner())
  File "/usr/local/lib/python3.6/dist-packages/bert_base/runs/__init__.py", line 38, in train_ner
    train(args=args)
  File "/usr/local/lib/python3.6/dist-packages/bert_base/train/bert_lstm_ner.py", line 618, in train
    early_stopping_hook = tf.contrib.estimator.stop_if_no_decrease_hook(
AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'

**Comment by zhaifly** [comment]
> > 1.13 or 1.14
> > TensorFlow -- 1.15.0
> > Traceback (most recent call last):
> > File "/usr/local/bin/bert-base-ner-train", line 8, in 
> > sys.exit(train_ner())
> > File "/usr/local/lib/python3.6/dist-packages/bert_base/runs/**init**.py", line 38, in train_ner
> > train(args=args)
> > File "/usr/local/lib/python3.6/dist-packages/bert_base/train/bert_lstm_ner.py", line 618, in train
> > early_stopping_hook = tf.contrib.estimator.stop_if_no_decrease_hook(
> > AttributeError: module 'tensorflow.contrib.estimator' has no attribute 'stop_if_no_decrease_hook'

```
-        early_stopping_hook = tf.estimator.experimental.stop_if_no_decrease_hook(
+        early_stopping_hook = tf.contrib.estimator.stop_if_no_decrease_hook(
```
