### ISSUE TITLE
EOFError: Ran out of input如何解决

### ISSUE THREAD

**Issue by naiynaiy** [macanv/BERT-BiLSTM-CRF-NER#400]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\ancanda_new\envs\tensorflow\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\ancanda_new\envs\tensorflow\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by naiynaiy** [comment]
TypeError: can't pickle _thread.RLock objects

**Comment by sen1orNWzZzZzZz** [comment]
我也是这个问题，如何解决？
