### ISSUE TITLE
https://github.com/macanv/BERT-BiLSTM-CRF-NER master clone下来的代码缺了很多东西

### ISSUE THREAD

**Issue by chros425** [macanv/BERT-BiLSTM-CRF-NER#47]
如题，https://github.com/macanv/BERT-BiLSTM-CRF-NER master clone下来的代码缺了很多东西，没有bert、train、NERdata等很多内容，麻烦大佬看下，是我下载的不对吗

**Comment by chros425** [comment]
想要训练自己的NER数据，发现源码中没有如bert_lstm_ner.py等文件

**Comment by macanv** [comment]
@chros425 那些都是以前的东西了，你可以是有pip 下载后，使用命令行的形式进行训练，，代码文件。。没有上传成功，年后吧~~，代码在学校机器上。

**Comment by chros425** [comment]
你好，我碰到以下问题，还麻烦您帮忙解答下，谢谢！
1、命令行的方式我尝试过，一直报下面的错误，我用的TensorFlow的版本是1.10.0，另外，1.11.0和1.12.0我都尝试过，都不行，报错信息如下，应该是这行代码用了d = d.apply(tf.data.experimental.map_and_batch 不支持的接口。
label:  O O O O O O O B-LOC I-LOC O B-LOC I-LOC O O O O O O
20864
label:  O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O
Traceback (most recent call last):
  File "/home/software/anaconda3/bin/bert-base-ner-train", line 11, in <module>
    sys.exit(train_ner())
  File "/home/software/anaconda3/lib/python3.6/site-packages/bert_base/runs/__init__.py", line 37, in train_ner
    train(args=args)
  File "/home/software/anaconda3/lib/python3.6/site-packages/bert_base/train/bert_lstm_ner.py", line 616, in train
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1167, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1011, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1100, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/software/anaconda3/lib/python3.6/site-packages/bert_base/train/bert_lstm_ner.py", line 329, in input_fn
    d = d.apply(tf.data.experimental.map_and_batch(lambda record: _decode_record(record, name_to_features),
AttributeError: module 'tensorflow.data' has no attribute 'experimental'

2、请问这个命令行的方式是否可以训练自己的数据，比如我新增加一些要识别的标签（10个新的标签），请问命令行的方式是否也可以训练和作为服务运行。
谢谢您！
