### ISSUE TITLE
使用命令行进行NER训练时报错 AttributeError: module 'tensorflow.data' has no attribute 'experimental'，TensorFlow版本1.10.0，另外1.11.0和1.12.0也尝试过，同样报错

### ISSUE THREAD

**Issue by chros425** [macanv/BERT-BiLSTM-CRF-NER#48]
大佬你好，我碰到以下问题，还麻烦您帮忙解答下，谢谢！
1、命令行的方式我尝试过，一直报下面的错误，我用的TensorFlow的版本是1.10.0，另外，1.11.0和1.12.0我都尝试过，都不行，用的是大佬提供的原始训练语料train.txt ，报错信息如下：
Traceback (most recent call last):
  File "/home/software/anaconda3/bin/bert-base-ner-train", line 11, in <module>
    sys.exit(train_ner())
  File "/home/software/anaconda3/lib/python3.6/site-packages/bert_base/runs/__init__.py", line 37, in train_ner
    train(args=args)
  File "/home/software/anaconda3/lib/python3.6/site-packages/bert_base/train/bert_lstm_ner.py", line 616, in train
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1167, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1011, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/software/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1100, in _call_input_fn
    return input_fn(**kwargs)
  File "/home/software/anaconda3/lib/python3.6/site-packages/bert_base/train/bert_lstm_ner.py", line 329, in input_fn
    d = d.apply(tf.data.experimental.map_and_batch(lambda record: _decode_record(record, name_to_features),
AttributeError: module 'tensorflow.data' has no attribute 'experimental'

**Comment by macanv** [comment]
1.12 实锤有，，，

**Comment by Lmerengues** [comment]
同问！这个问题解决了没？

**Comment by macanv** [comment]
这就不是问题，为啥不确认一下官方api并且check一下自己的环境呢？

**Comment by semal** [comment]
using tf 1.12, working..

**Comment by 18813055625** [comment]
除了升级版本，还有其他的解决方法吗

**Comment by Windy-Ground** [comment]
1.10.0里面：tf.contrib.data.map_and_batch，1.13及后面都改成tf.data了

**Comment by ianliuy** [comment]
参考stop_if_no_decrease_hook的文档
https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/estimator/experimental/stop_if_no_decrease_hook

简单地说，pip install tensorflow==1.15就肯定没问题了~
