### ISSUE TITLE
运行报错，缺少bert_config.json文件

### ISSUE THREAD

**Issue by mazicwong** [macanv/BERT-BiLSTM-CRF-NER#53]
执行的命令
```
bert-base-ner-train \
            -data_dir {~/bert_test/data/}\
            -output_dir {~/bert_test/output/}\
            -init_checkpoint {~/bert_test/uncased_L-12_H-768_A-12/}\
            -bert_config_file {~/bert_test/uncased_L-12_H-768_A-12/bert_config.json} \
            -vocab_file {~/bert_test/uncased_L-12_H-768_A-12/vocab.txt}
```

报错：
```
Traceback (most recent call last):
  File "/home/hzq/anaconda3/envs/tensorflow/bin/bert-base-ner-train", line 11, in <module>
    load_entry_point('bert-base==0.0.6', 'console_scripts', 'bert-base-ner-train')()
  File "/home/hzq/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bert_base-0.0.6-py3.6.egg/bert_base/runs/__init__.py", line 38, in train_ner
    train(args=args)
  File "/home/hzq/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bert_base-0.0.6-py3.6.egg/bert_base/train/bert_lstm_ner.py", line 494, in train
    bert_config = modeling.BertConfig.from_json_file(args.bert_config_file)
  File "/home/hzq/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bert_base-0.0.6-py3.6.egg/bert_base/bert/modeling.py", line 93, in from_json_file
    text = reader.read()
  File "/home/hzq/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    self._preread_check()
  File "/home/hzq/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/hzq/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: {~/bert_test/uncased_L-12_H-768_A-12/bert_config.json}; No such file or directory
```
求助为什么会读取不到bert的配置文件, 直接从bert官方下载的

**Comment by macanv** [comment]
额，{ } 这两个符合去掉吧~~

**Comment by mazicwong** [comment]
hhh傻了 谢谢🙏
