### ISSUE TITLE
运行过程有报错

### ISSUE THREAD

**Issue by wangyingshuai** [macanv/BERT-BiLSTM-CRF-NER#6]
楼主，您好，有以下报错，请问data.conf这个文件是您忘了上传了吗？还是我需要配置成什么样子的？
Traceback (most recent call last):
  File "bert_lstm_ner.py", line 815, in <module>
    tf.app.run()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "bert_lstm_ner.py", line 724, in main
    with codecs.open(FLAGS.data_config_path, 'a', encoding='utf-8') as fd:
  File "/usr/local/anaconda3/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wangyingshuai/BERT-BiLSMT-CRF-NER/data.conf'

**Comment by macanv** [comment]
data_conf 是我为了避免每次train的时候都需要从新生成tf_record 文件而增加的，你也可以没必要理会这个，每次直接delete掉这个文件和output中的所有文件。
