### ISSUE TITLE
运行bert-base-serving-start，生成PB文件异常

### ISSUE THREAD

**Issue by huangxz** [macanv/BERT-BiLSTM-CRF-NER#61]
您好，今天重新训练一个模型（语料都一样），再启动服务生成PB文件的时候异常，错误信息如下：
Use standard file APIs to check for files with this prefix.
E:NER_MODEL, Lodding...:[gra:opt:306]:fail to optimize the graph! Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
	 [[node save/Assign_199 (defined at /usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py:291) ]]

Caused by op 'save/Assign_199', defined at:
  File "/usr/local/bin/bert-base-serving-start", line 10, in <module>
    sys.exit(start_server())
  File "/usr/local/lib/python3.6/dist-packages/bert_base/runs/__init__.py", line 17, in start_server
    server = BertServer(args)
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/__init__.py", line 92, in __init__
    with Pool(processes=1) as pool:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 175, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py", line 291, in optimize_ner_model
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
	 [[node save/Assign_199 (defined at /usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py:291) ]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
	 [[{{node save/Assign_199}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
	 [[node save/Assign_199 (defined at /usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py:291) ]]

Caused by op 'save/Assign_199', defined at:
  File "/usr/local/bin/bert-base-serving-start", line 10, in <module>
    sys.exit(start_server())
  File "/usr/local/lib/python3.6/dist-packages/bert_base/runs/__init__.py", line 17, in start_server
    server = BertServer(args)
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/__init__.py", line 92, in __init__
    with Pool(processes=1) as pool:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 175, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py", line 291, in optimize_ner_model
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
	 [[node save/Assign_199 (defined at /usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py:291) ]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py", line 295, in optimize_ner_model
    saver.restore(sess, tf.train.latest_checkpoint(args.model_dir))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1312, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
	 [[node save/Assign_199 (defined at /usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py:291) ]]

Caused by op 'save/Assign_199', defined at:
  File "/usr/local/bin/bert-base-serving-start", line 10, in <module>
    sys.exit(start_server())
  File "/usr/local/lib/python3.6/dist-packages/bert_base/runs/__init__.py", line 17, in start_server
    server = BertServer(args)
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/__init__.py", line 92, in __init__
    with Pool(processes=1) as pool:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 175, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 236, in _repopulate_pool
    self._wrap_exception)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 255, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py", line 291, in optimize_ner_model
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 354, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 73, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
	 [[node save/Assign_199 (defined at /usr/local/lib/python3.6/dist-packages/bert_base/server/graph.py:291) ]]

Traceback (most recent call last):
  File "/usr/local/bin/bert-base-serving-start", line 10, in <module>
    sys.exit(start_server())
  File "/usr/local/lib/python3.6/dist-packages/bert_base/runs/__init__.py", line 17, in start_server
    server = BertServer(args)
  File "/usr/local/lib/python3.6/dist-packages/bert_base/server/__init__.py", line 102, in __init__
    raise FileNotFoundError('graph optimization fails and returns empty result')
FileNotFoundError: graph optimization fails and returns empty result

**Comment by macanv** [comment]
确认一下，bert_base/server/init.py文件中，97行中的num_label 和你训练的时候模型的num_labels相同。

**Comment by huangxz** [comment]
您好，num_label 和训练时候模型的num_labels是一样的

**Comment by huangxz** [comment]
在 saver.restore(sess, tf.train.latest_checkpoint(args.model_dir))  在这抛出的异常

**Comment by macanv** [comment]
Assign requires shapes of both tensors to match. lhs shape= [44,44] rhs shape= [45,45]
错误是这里吧，我猜想你的训练模型中是45个标签，而在这里，你传的是44个标签大小。

**Comment by huangxz** [comment]
标签，我没有通过参数配置，都是从训练模型读取的，如果这样的话，那有可能是获取标签那边，我再测试一下

**Comment by macanv** [comment]
Sorry ，这是一个bug,请先卸载掉bert_base,然后修改bert_base/server/__init__.py的第97行（num_labels改动为self.num_labels)
```
self.graph_path = pool.apply(optimize_ner_model, (self.args, self.num_labels))
```
然后重新使用源码安装的方式进行install，再进行其他操作。
不好意思~

**Comment by Single430** [comment]
你好，请问你是如何保存ｐｂ文件的，这部分我还不是很熟悉

**Comment by huangxz** [comment]
好的，感谢作者的耐心

**Comment by huangxz** [comment]
@Single430  ｐｂ文件保存运行作者的start service 就会自动生成，看作者的文档，他写的很详细

**Comment by Single430** [comment]
@huangxz 　　我是使用这个命令　bert-base-ner-train　　进行训练的，输出并未有pb文件保存

**Comment by huangxz** [comment]
bert-base-serving-start \
    -model_dir C:\workspace\python\BERT_Base\output\ner2 \
    -bert_model_dir F:\chinese_L-12_H-768_A-12
    -model_pb_dir C:\workspace\python\BERT_Base\model_pb_dir
    -mode NER

**Comment by chenbaicheng** [comment]
@huangxz   那个 我输入-model_pb_dir    它提示这个argument无效的   版本已经是0.9.0了 你没有遇到错误提示吗

**Comment by xxllp** [comment]
这个问题还是存在哈

**Comment by zwd13122889** [comment]
> @huangxz 那个 我输入-model_pb_dir 它提示这个argument无效的 版本已经是0.9.0了 你没有遇到错误提示吗

你好，我也遇到了这个问题，请问你是怎么解决的

**Comment by zwd13122889** [comment]
> @huangxz 那个 我输入-model_pb_dir 它提示这个argument无效的 版本已经是0.9.0了 你没有遇到错误提示吗

我也遇到同样的问题，请问你是怎么解决的

**Comment by Single430** [comment]
@zwd13122889    可以不用作者的命令来生成pb文件，查看`/youpath/site-packages/bert_base/server/graph.py`  309行 `optimize_class_model` 函数自己摘出来做一点点修改就行

**Comment by zwd13122889** [comment]
> @zwd13122889 可以不用作者的命令来生成pb文件，查看`/youpath/site-packages/bert_base/server/graph.py` 309行 `optimize_class_model` 函数自己摘出来做一点点修改就行

我训练出来的模型是针对英文的，那么我想请教下该如何改呢？对这方面不是恨熟悉

**Comment by Single430** [comment]
@zwd13122889   跟语言没关系
