### ISSUE TITLE
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory chinese_L-12_H-768_A-12

### ISSUE THREAD

**Issue by Zengpr** [macanv/BERT-BiLSTM-CRF-NER#84]
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory chinese_L-12_H-768_A-12

**Comment by cellslogic** [comment]
the same...

**Comment by macanv** [comment]
could you private more information?

**Comment by cellslogic** [comment]
> could you private more information?

    bert-base-ner-train -data_dir D:\dev\src\work\spider\ner -output_dir D:\dev\src\work\spider\output -init_checkpoint=D:\chinese_L-12_H-768_A-12 -bert_config_file D:\chinese_L-12_H-768_A-12\bert_config.json -vocab_file D:\chinese_L-12_H-768_A-12\vocab.txt
usage: D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\Scripts\bert-base-ner-train -data_dir D:\dev\src\work\spider\ner -output_dir D:\dev\src\work\spider\output -init_checkpoint=D:\chinese_L-12_H-768_A-12 -bert_config_file D:\chinese_L-12_H-768_A-12\bert_config.json -vocab_file D:\chinese_L-12_H-768_A-12\vocab.txt
                 ARG   VALUE
__________________________________________________
          batch_size = 64
    bert_config_file = D:\chinese_L-12_H-768_A-12\bert_config.json
                cell = lstm
               clean = True
                clip = 0.5
            data_dir = D:\dev\src\work\spider\ner
          device_map = 0
             do_eval = True
       do_lower_case = True
          do_predict = True
            do_train = True
        dropout_rate = 0.5
     filter_adam_var = False
     init_checkpoint = D:\chinese_L-12_H-768_A-12
          label_list = None
       learning_rate = 1e-05
           lstm_size = 128
      max_seq_length = 128
                 ner = ner
          num_layers = 1
    num_train_epochs = 10
          output_dir = D:\dev\src\work\spider\output
save_checkpoints_steps = 500
  save_summary_steps = 500
             verbose = False
          vocab_file = D:\chinese_L-12_H-768_A-12\vocab.txt
   warmup_proportion = 0.1

shape of input_ids (64, 128)
Traceback (most recent call last):
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\Scripts\bert-base-ner-train-script.py", line 11, in <module>
    load_entry_point('bert-base==0.0.9', 'console_scripts', 'bert-base-ner-train')()
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\bert_base-0.0.9-py3.6.egg\bert_base\runs\__init__.py", line 38, in train_ner
    train(args=args)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\bert_base-0.0.9-py3.6.egg\bert_base\train\bert_lstm_ner.py", line 639, in train
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\estimator\training.py", line 471, in train_and_evaluate
    return executor.run()
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\estimator\training.py", line 610, in run
    return self.run_local()
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\estimator\training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\estimator\estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\estimator\estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\bert_base-0.0.9-py3.6.egg\bert_base\train\bert_lstm_ner.py", line 401, in model_fn
    init_checkpoint)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\bert_base-0.0.9-py3.6.egg\bert_base\bert\modeling.py", line 331, in get_assignment_map_from_checkpoint
    init_vars = tf.train.list_variables(init_checkpoint)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 95, in list_variables
    reader = load_checkpoint(ckpt_dir_or_file)
  File "D:\dev\python\Anaconda3\envs\tensorflow-gpu1.12\lib\site-packages\tensorflow\python\training\checkpoint_utils.py", line 63, in load_checkpoint
    "given directory %s" % ckpt_dir_or_file)
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory D:\chinese_L-12_H-768_A-12

**Comment by macanv** [comment]
```
init_checkpoint = D:\chinese_L-12_H-768_A-12\bert_model.ckpt
```

**Comment by cellslogic** [comment]
> ```
> init_checkpoint = D:\chinese_L-12_H-768_A-12\bert_model.ckpt
> ```
                 ARG   VALUE
__________________________________________________
          batch_size = 64
    bert_config_file = /home/deep/dev/chinese_L-12_H-768_A-12/bert_config.json
                cell = lstm
               clean = True
                clip = 0.5
            data_dir = /home/deep/dev/ner
          device_map = 0
             do_eval = True
       do_lower_case = True
          do_predict = True
            do_train = True
        dropout_rate = 0.5
     filter_adam_var = False
     init_checkpoint = /home/deep/dev/chinese_L-12_H-768_A-12/bert_model.ckpt
          label_list = None
       learning_rate = 1e-05
           lstm_size = 128
      max_seq_length = 128
                 ner = ner
          num_layers = 1
    num_train_epochs = 10
          output_dir = /home/deep/dev/output
save_checkpoints_steps = 500
  save_summary_steps = 500
             verbose = False
          vocab_file = /home/deep/dev/chinese_L-12_H-768_A-12/vocab.txt
   warmup_proportion = 0.1

shape of input_ids (64, 128)
2019-03-11 10:48:20.122377: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-11 10:48:20.444126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
totalMemory: 7.93GiB freeMemory: 7.63GiB
2019-03-11 10:48:20.444208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-03-11 10:48:24.749573: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-11 10:48:24.749659: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-03-11 10:48:24.749689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-03-11 10:48:24.750185: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7365 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-03-11 10:49:02.041045: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed to alloc 4294967296 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-11 10:49:02.041205: W ./tensorflow/core/common_runtime/gpu/cuda_host_allocator.h:44] could not allocate pinned host memory of size: 4294967296
2019-03-11 10:49:02.041336: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed to alloc 3865470464 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-11 10:49:02.041368: W ./tensorflow/core/common_runtime/gpu/cuda_host_allocator.h:44] could not allocate pinned host memory of size: 3865470464
2019-03-11 10:49:02.041443: E tensorflow/stream_executor/cuda/cuda_driver.cc:868] failed to alloc 3478923264 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-03-11 10:49:02.041471: W ./tensorflow/core/common_runtime/gpu/cuda_host_allocator.h:44] could not allocate pinned host memory of size: 3478923264
Killed

help...

**Comment by macanv** [comment]
你的显卡显存太小的问题，查看一下其他的issue

**Comment by liushaoqian** [comment]
> ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory chinese_L-12_H-768_A-12 ![2019-03-08 17-15-23](https://user-images.githubusercontent.com/22451062/54019490-49dc1180-41c6-11e9-9ac6-962f10b82637.png)

你这个问题后面怎么解决的啊
