### ISSUE TITLE
求问一下tensorflow的版本

### ISSUE THREAD

**Issue by bluesky632** [macanv/BERT-BiLSTM-CRF-NER#87]
\BERT-BiLSTM-CRF-NER-master>bert-base-ner-train -help
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\bert-base-ner-train-script.py", line 11, in <module>
    load_entry_point('bert-base==0.0.8', 'console_scripts', 'bert-base-ner-train')()
  File "d:\anaconda3\lib\site-packages\bert_base-0.0.8-py3.6.egg\bert_base\runs\__init__.py", line 29, in train_ner
    from bert_base.train.bert_lstm_ner import train
  File "d:\anaconda3\lib\site-packages\bert_base-0.0.8-py3.6.egg\bert_base\train\bert_lstm_ner.py", line 18, in <module>
    import tensorflow as tf
  File "d:\anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "d:\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 82, in <module>
    from tensorflow.python import keras
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\activations\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.activations import elu
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\__init__.py", line 21, in <module>
    from tensorflow.python.keras._impl.keras import activations
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\activations.py", line 23, in <module>
    from tensorflow.python.keras._impl.keras import backend as K
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py", line 36, in <module>
    from tensorflow.python.layers import base as tf_base_layers
  File "d:\anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 25, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\engine\__init__.py", line 23, in <module>
    from tensorflow.python.keras.engine.base_layer import Layer
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 34, in <module>
    from tensorflow.python.keras import backend
  File "d:\anaconda3\lib\site-packages\tensorflow\python\keras\backend\__init__.py", line 22, in <module>
    from tensorflow.python.keras._impl.keras.backend import abs
ImportError: cannot import name 'abs'
安装完居然报了这个错误，是不是tensorflow版本有问题？

**Comment by macanv** [comment]
require.txt里面有些，麻烦大家在提问的时候能自己先看看么？不是这样学习的吧。。。

**Comment by bluesky632** [comment]
谢谢，当时太粗心了，没有仔细看代码，问题已经解决了
